
#load libraries (install if necessary)

install.packages(c("ggfortify", "tidyr", "plyr", "dplyr", "devtools", "ggsci","mdatools","EEM","spectacles","ids","rgl","tiff","grid","terra","rgdal",
                   "rgeos","SDMTools","remotes", "signal", "ggpubr", "hyperSpec","rasterVis", "Rcpp", "raster", "tidyverse"))

library(ggfortify)
library(tidyr)
library(plyr)
library(dplyr)
library(devtools)
library(ggsci)
library(mdatools)
library(EEM)
library(readxl)
library(spectacles)
library(ids)
library(rgl)
library(tiff)
library(grid)
library(terra)
library(rgdal)
library(rgeos)
library(SDMTools)
library(remotes)
library(signal)
library(ggpubr)
library(hyperSpec)
library(rasterVis)
library(Rcpp)
library(raster)
library(tidyverse)
