
#load libraries (install if necessary)

library(readr)
library(ggplot2)
library(ggfortify)
library(tidyr)
library(plyr)
library(dplyr)
library(devtools)
library(ggsci)
library(mdatools)
library(EEM)
library(readxl)
library(spectacles)
library(ids)
library(rgl)
library(png)
library(tiff)
library(grid)
library(terra)
library(rgdal)
library(rgeos)
library(SDMTools)
library(remotes)
library(signal)
library(ggpubr)
library(hyperSpec)
library(rasterVis)
library(Rcpp)
library(raster)
library(viridis)
library(tidyverse)
